# name of pipeline workflow
name: Amit terraform workflow 
# trigger action 
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "main" ]  
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"
# creating jobs
jobs:
# stage 1 with terraform details
  infra-provision-job: 
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    #calling first github action to clone my dryrun-aws data to runner machine
    - name: taking code from my repo
      uses: actions/checkout@v5
      with:
        ref: main
#installing terraform
    - name: installing terraform
      uses: hashicorp/setup-terraform@v3
#running some commands
    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version
        whoami
        ls -a
        terraform version
#configure aws secret keys
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: verify aws connection
      run: |
        echo "checking with command"
        aws s3 ls

    - name: deploy terraform resources
      run: |
        echo "implementing terraform deals"
        terraform init 
        terraform plan
        sleep 2
        terraform apply --auto-approve
        ls modules/ec2
# creating artifact and uploading ansible inventory file
    - name: uploading ansible inventory to github repo 
      uses: actions/upload-artifact@v4
      with:
        name: amit-github-artifact
        path: modules/ec2/ansible-inventory.txt


  infra-destroy-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
    - name: checking out code
      uses: actions/checkout@v5
      with:
        ref: main

    - name: Login AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
#downloading artifact the one I created above
    - name: downloading ansible inventory from artifact
      uses: actions/download-artifact@v5
      with:
        name: amit-github-artifact
    - name: displaying structure if downloading files
      run: ls -R

    - name: installing terraform
      uses: hashicorp/setup-terraform@v3

    - name: destroying terraform infra
      run: |
        echo "checking resoruces"
        terraform init 
        terraform state list
        terraform destroy --auto-approve



